modLoader="javafml"
loaderVersion="[28,)"
license="Apache-2.0"
issueTrackerURL="https://git.io/JfhAe"

[[mods]]
modId="controlshift"
version="${file.jarVersion}"
displayName="Control Shift"
displayURL="https://git.io/JfhNj"
authors="Chloe Dawn"
description='''Swaps the default sneaking and sprinting key bindings'''

[[dependencies.controlshift]]
modId="minecraft"
mandatory=true
versionRange="[1.14,1.17)"
side="CLIENT"

[[dependencies.controlshift]]
modId="forge"
mandatory=true
versionRange="[28,)"
side="CLIENT"
